import { test, expect } from '@playwright/test'

test('discover, save, match, and message on both layouts', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Your next first, together.' })).toBeVisible()
  await page.getByPlaceholder('Search a class, studio, or neighborhood').fill('pottery')
  await expect(page.getByRole('article')).toHaveCount(1)
  await page.getByRole('button', { name: 'Save class', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Remove from saved' })).toBeVisible()
  await page.getByRole('button', { name: 'Find a buddy', exact: true }).click()
  await page.getByRole('button', { name: 'Interested', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Say hello' })).toBeVisible()
  await page.getByRole('button', { name: 'Say hello' }).click()
  const input = page.locator('textarea, input').filter({ visible: true }).first()
  await input.fill('Excited to try this together!')
  await page.getByRole('button', { name: 'Send message' }).click()
  await expect(page.getByText('Excited to try this together!', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Suggest a session', exact: true }).click()
  await page.getByRole('button', { name: 'Send suggestion' }).click()
  await page.getByRole('button', { name: /Simulate .*reply/ }).click()
  await expect(page.getByText("You're on. Time to grab your spots.")).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: `test-results/${test.info().project.name}-chat.png`, fullPage: true })
  expect(errors).toEqual([])
})

test('PWA manifest and offline navigation', async ({ page, context, request }) => {
  const manifest = await (await request.get('/manifest.webmanifest')).json()
  expect(manifest.display).toBe('standalone')
  for (const icon of manifest.icons) expect((await request.get(icon.src)).ok()).toBeTruthy()
  await page.goto('/')
  await page.evaluate(() => navigator.serviceWorker.ready)
  await page.reload()
  await context.setOffline(true)
  await page.goto('/offline-check')
  await expect(page.getByRole('heading', { name: 'Let’s reconnect.' })).toBeVisible()
})
