import type {
  Buddy,
  Category,
  ClassListing,
  Conversation,
  UserProfile,
} from './types'

export const CATEGORIES: (Category | 'All')[] = [
  'All',
  'Pottery',
  'Cooking',
  'Dance',
  'Climbing',
  'Art',
  'Outdoors',
]

export const NEIGHBORHOODS = [
  'Any neighborhood',
  'Cambridge',
  'Somerville',
  'Back Bay',
  'South End',
  'Jamaica Plain',
  'Allston',
  'North End',
  'Beacon Hill',
  'Fenway',
]

export const AVAILABILITY_OPTIONS = [
  'Weekday mornings',
  'Weekday evenings',
  'Saturday mornings',
  'Saturday afternoons',
  'Sunday afternoons',
  'Sunday evenings',
]

export const DATE_RANGES = [
  'This week',
  'Next 2 weeks',
  'This month',
  'I’m flexible',
]

export const IMG = {
  pottery: '/images/activities/pottery.png',
  pasta: '/images/activities/pasta.png',
  dance: '/images/activities/dance.png',
  climbing: '/images/activities/climbing.png',
  painting: '/images/activities/painting.png',
  hiking: '/images/activities/hiking.png',
  film: '/images/activities/film-photography.png',
  bread: '/images/activities/bread.png',
  watercolor: '/images/activities/watercolor.png',
  salsa: '/images/activities/salsa.png',
  kayak: '/images/activities/kayak.png',
  jewelry: '/images/activities/jewelry.png',
}

export const CLASSES: ClassListing[] = [
  {
    id: 'wheel-throwing',
    title: 'Wheel Throwing for Total Beginners',
    provider: 'Mudroom Clay Studio',
    category: 'Pottery',
    subject: 'pottery',
    neighborhood: 'Somerville',
    image: IMG.pottery,
    pricePerPerson: 65,
    durationMins: 120,
    level: 'Beginner',
    beginnerFriendly: true,
    blurb: 'Center your first lump of clay and leave with a wobbly bowl you’re weirdly proud of.',
    whatYoullDo: [
      'Learn to wedge, center, and pull your first walls',
      'Throw two small vessels on the wheel',
      'Trim and set aside pieces for studio glazing',
    ],
    included: ['All clay and tools', 'Studio firing', 'An apron to borrow'],
    requirements: 'No experience needed. Wear clothes you don’t mind getting muddy.',
    sessions: [
      { id: 's1', date: '2026-09-20T00:00:00', time: '10:00 AM', timeOfDay: 'Morning' },
      { id: 's2', date: '2026-09-24T00:00:00', time: '6:30 PM', timeOfDay: 'Evening' },
      { id: 's3', date: '2026-09-27T00:00:00', time: '2:00 PM', timeOfDay: 'Afternoon' },
    ],
    interestedCount: 34,
  },
  {
    id: 'fresh-pasta',
    title: 'Fresh Pasta Night',
    provider: 'Tavola Cucina',
    category: 'Cooking',
    subject: 'pasta making',
    neighborhood: 'North End',
    image: IMG.pasta,
    pricePerPerson: 78,
    durationMins: 150,
    level: 'All levels',
    beginnerFriendly: true,
    blurb: 'Roll, cut, and twirl your own tagliatelle, then sit down and eat the whole thing.',
    whatYoullDo: [
      'Make egg dough by hand and rest it',
      'Roll and cut two pasta shapes',
      'Cook a simple seasonal sauce and share a table',
    ],
    included: ['All ingredients', 'A glass of wine or spritz', 'Recipe cards to take home'],
    requirements: 'All levels welcome. Let them know about allergies when you plan.',
    sessions: [
      { id: 's1', date: '2026-09-19T00:00:00', time: '6:00 PM', timeOfDay: 'Evening' },
      { id: 's2', date: '2026-09-26T00:00:00', time: '6:00 PM', timeOfDay: 'Evening' },
    ],
    interestedCount: 51,
  },
  {
    id: 'contemporary-dance',
    title: 'Contemporary Dance: Move & Play',
    provider: 'Fieldhouse Movement Lab',
    category: 'Dance',
    subject: 'contemporary dance',
    neighborhood: 'Cambridge',
    image: IMG.dance,
    pricePerPerson: 32,
    durationMins: 75,
    level: 'Beginner',
    beginnerFriendly: true,
    blurb: 'A low-pressure hour of guided movement. No mirrors-and-judgment energy here.',
    whatYoullDo: [
      'Warm up with simple guided phrases',
      'Explore weight, momentum, and floor work',
      'Improvise in a short, friendly group flow',
    ],
    included: ['Sprung studio floor', 'Water', 'Socks if you forget yours'],
    requirements: 'Beginner friendly. Wear comfy clothes you can stretch in.',
    sessions: [
      { id: 's1', date: '2026-09-18T00:00:00', time: '7:00 PM', timeOfDay: 'Evening' },
      { id: 's2', date: '2026-09-22T00:00:00', time: '7:00 PM', timeOfDay: 'Evening' },
      { id: 's3', date: '2026-09-25T00:00:00', time: '9:30 AM', timeOfDay: 'Morning' },
    ],
    interestedCount: 22,
  },
  {
    id: 'intro-bouldering',
    title: 'Intro to Bouldering',
    provider: 'Granite & Chalk',
    category: 'Climbing',
    subject: 'bouldering',
    neighborhood: 'Somerville',
    image: IMG.climbing,
    pricePerPerson: 40,
    durationMins: 90,
    level: 'Beginner',
    beginnerFriendly: true,
    blurb: 'Learn to fall safely, read a route, and send your first colorful problem.',
    whatYoullDo: [
      'Cover falling and spotting basics',
      'Warm up on beginner problems',
      'Project a route or two with your buddy',
    ],
    included: ['Day pass', 'Shoe rental', 'Chalk'],
    requirements: 'No experience needed. Bring athletic clothes and a water bottle.',
    sessions: [
      { id: 's1', date: '2026-09-21T00:00:00', time: '11:00 AM', timeOfDay: 'Morning' },
      { id: 's2', date: '2026-09-23T00:00:00', time: '6:00 PM', timeOfDay: 'Evening' },
    ],
    interestedCount: 47,
  },
  {
    id: 'bold-acrylics',
    title: 'Loose & Bold Acrylics',
    provider: 'Southpaw Art Room',
    category: 'Art',
    subject: 'acrylic painting',
    neighborhood: 'South End',
    image: IMG.painting,
    pricePerPerson: 48,
    durationMins: 120,
    level: 'All levels',
    beginnerFriendly: true,
    blurb: 'Big brushes, warm colors, zero preciousness. Make one canvas you actually like.',
    whatYoullDo: [
      'Play with color mixing and mark making',
      'Build a loose abstract composition',
      'Finish one 16x20 canvas to take home',
    ],
    included: ['Canvas and paints', 'All brushes', 'Tea and snacks'],
    requirements: 'All levels. Aprons provided; wear something splash-friendly.',
    sessions: [
      { id: 's1', date: '2026-09-20T00:00:00', time: '1:00 PM', timeOfDay: 'Afternoon' },
      { id: 's2', date: '2026-09-28T00:00:00', time: '1:00 PM', timeOfDay: 'Afternoon' },
    ],
    interestedCount: 29,
  },
  {
    id: 'blue-hills-hike',
    title: 'Blue Hills Sunrise Hike',
    provider: 'Trailmates Boston',
    category: 'Outdoors',
    subject: 'hiking',
    neighborhood: 'Milton',
    image: IMG.hiking,
    pricePerPerson: 18,
    durationMins: 180,
    level: 'All levels',
    beginnerFriendly: true,
    blurb: 'A guided morning climb to Great Blue Hill with a skyline view as your reward.',
    whatYoullDo: [
      'Meet at the trailhead for a warm welcome',
      'Hike a moderate loop with plenty of breaks',
      'Catch the Boston skyline from the observation tower',
    ],
    included: ['Certified guide', 'Trail snacks', 'A post-hike coffee stop'],
    requirements: 'Moderate pace. Bring sturdy shoes and a light layer.',
    sessions: [
      { id: 's1', date: '2026-09-21T00:00:00', time: '6:30 AM', timeOfDay: 'Morning' },
      { id: 's2', date: '2026-09-27T00:00:00', time: '6:30 AM', timeOfDay: 'Morning' },
    ],
    interestedCount: 38,
  },
  {
    id: 'shoot-film',
    title: 'Shoot Film in the City',
    provider: 'Grain & Light Co.',
    category: 'Art',
    subject: 'film photography',
    neighborhood: 'Cambridge',
    image: IMG.film,
    pricePerPerson: 55,
    durationMins: 120,
    level: 'Beginner',
    beginnerFriendly: true,
    blurb: 'Load a roll, wander Kendall, and learn to see light on a walk-and-shoot.',
    whatYoullDo: [
      'Learn your camera and basic exposure',
      'Walk and shoot a roll around Kendall Square',
      'Drop film for developing and swap contacts',
    ],
    included: ['Loaner film camera', 'One roll of film', 'Developing coupon'],
    requirements: 'Beginner friendly. Bring a phone for notes and comfy walking shoes.',
    sessions: [
      { id: 's1', date: '2026-09-22T00:00:00', time: '3:00 PM', timeOfDay: 'Afternoon' },
      { id: 's2', date: '2026-09-29T00:00:00', time: '3:00 PM', timeOfDay: 'Afternoon' },
    ],
    interestedCount: 26,
  },
  {
    id: 'sourdough',
    title: 'Sourdough from Scratch',
    provider: 'Wildyeast Bakehouse',
    category: 'Cooking',
    subject: 'bread baking',
    neighborhood: 'Jamaica Plain',
    image: IMG.bread,
    pricePerPerson: 70,
    durationMins: 180,
    level: 'All levels',
    beginnerFriendly: true,
    blurb: 'Shape and score a real loaf, and go home with a starter of your own to name.',
    whatYoullDo: [
      'Understand starter, hydration, and timing',
      'Shape and score a boule together',
      'Take home a starter and a warm loaf',
    ],
    included: ['A jar of starter', 'Your baked loaf', 'Printed formula'],
    requirements: 'All levels. Some standing time; snacks provided throughout.',
    sessions: [
      { id: 's1', date: '2026-09-20T00:00:00', time: '9:00 AM', timeOfDay: 'Morning' },
      { id: 's2', date: '2026-09-26T00:00:00', time: '9:00 AM', timeOfDay: 'Morning' },
    ],
    interestedCount: 33,
  },
  {
    id: 'botanical-watercolor',
    title: 'Botanical Watercolor Basics',
    provider: 'Fernleaf Studio',
    category: 'Art',
    subject: 'watercolor',
    neighborhood: 'Cambridge',
    image: IMG.watercolor,
    pricePerPerson: 44,
    durationMins: 105,
    level: 'Beginner',
    beginnerFriendly: true,
    blurb: 'Soft washes, single stems, and a calm afternoon of paint and quiet company.',
    whatYoullDo: [
      'Practice washes, blooms, and layering',
      'Paint two simple botanical studies',
      'Leave with a small framed piece',
    ],
    included: ['Watercolor paper', 'Paints and brushes', 'A frame for one study'],
    requirements: 'Beginner friendly. Just bring yourself.',
    sessions: [
      { id: 's1', date: '2026-09-19T00:00:00', time: '2:30 PM', timeOfDay: 'Afternoon' },
      { id: 's2', date: '2026-09-24T00:00:00', time: '2:30 PM', timeOfDay: 'Afternoon' },
    ],
    interestedCount: 41,
  },
  {
    id: 'salsa-social',
    title: 'Salsa Social for Beginners',
    provider: 'Ritmo Dance Collective',
    category: 'Dance',
    subject: 'salsa',
    neighborhood: 'Allston',
    image: IMG.salsa,
    pricePerPerson: 25,
    durationMins: 120,
    level: 'Beginner',
    beginnerFriendly: true,
    blurb: 'A friendly lesson, then an open floor with string lights and zero pressure.',
    whatYoullDo: [
      'Learn the basic step and a simple turn',
      'Rotate partners in a relaxed lesson',
      'Stay for the social and practice',
    ],
    included: ['Beginner lesson', 'Social entry', 'One drink ticket'],
    requirements: 'No partner or experience needed. Wear shoes you can pivot in.',
    sessions: [
      { id: 's1', date: '2026-09-19T00:00:00', time: '8:00 PM', timeOfDay: 'Evening' },
      { id: 's2', date: '2026-09-26T00:00:00', time: '8:00 PM', timeOfDay: 'Evening' },
    ],
    interestedCount: 44,
  },
  {
    id: 'charles-kayak',
    title: 'Charles River Kayak Basics',
    provider: 'Esplanade Paddle Club',
    category: 'Outdoors',
    subject: 'kayaking',
    neighborhood: 'Back Bay',
    image: IMG.kayak,
    pricePerPerson: 38,
    durationMins: 90,
    level: 'Beginner',
    beginnerFriendly: true,
    blurb: 'Learn to paddle straight, then glide the Charles with the skyline beside you.',
    whatYoullDo: [
      'Cover paddle strokes and safety on land',
      'Practice in the calm basin',
      'Paddle a short guided loop together',
    ],
    included: ['Kayak and paddle', 'Life vest', 'Certified guide'],
    requirements: 'Must be comfortable in water. Bring a change of clothes.',
    sessions: [
      { id: 's1', date: '2026-09-21T00:00:00', time: '10:00 AM', timeOfDay: 'Morning' },
      { id: 's2', date: '2026-09-27T00:00:00', time: '4:00 PM', timeOfDay: 'Afternoon' },
    ],
    interestedCount: 30,
  },
  {
    id: 'brass-ring',
    title: 'Make a Brass Ring',
    provider: 'Forge & Filament',
    category: 'Art',
    subject: 'jewelry making',
    neighborhood: 'Somerville',
    image: IMG.jewelry,
    pricePerPerson: 60,
    durationMins: 120,
    level: 'Beginner',
    beginnerFriendly: true,
    blurb: 'Saw, file, and sand a brass ring to fit, and walk out wearing what you made.',
    whatYoullDo: [
      'Measure and cut brass stock',
      'Shape, solder, and finish your ring',
      'Polish it to a warm shine',
    ],
    included: ['Metal and tools', 'Bench time', 'Safety gear'],
    requirements: 'Beginner friendly. Closed-toe shoes required at the bench.',
    sessions: [
      { id: 's1', date: '2026-09-23T00:00:00', time: '6:30 PM', timeOfDay: 'Evening' },
      { id: 's2', date: '2026-09-28T00:00:00', time: '11:00 AM', timeOfDay: 'Morning' },
    ],
    interestedCount: 19,
  },
]

export const BUDDIES: Buddy[] = [
  {
    id: 'maya',
    firstName: 'Maya',
    age: 27,
    neighborhood: 'Cambridge',
    photo: '/images/people/maya.png',
    gallery: [IMG.pottery, IMG.film, IMG.pasta],
    wantsToTryClassId: 'wheel-throwing',
    wantsToTryLabel: 'Wheel throwing for beginners',
    availability: ['Saturday afternoons', 'Weekday evenings'],
    bio: 'Product designer who moved here last spring. Trying to make things with my hands after staring at a screen all week.',
    headlinePrompt: 'Looking for someone equally prepared to make a very ugly bowl.',
    interests: ['film photography', 'climbing', 'pasta making', 'thrifting'],
    sharedInterests: ['pottery', 'film photography'],
    reason: 'You’re both pottery beginners and free Saturday afternoons.',
    socialPace: 'Coffee afterward',
    intentions: 'Wants a low-key regular buddy for weekend classes, not a whole friend group at once.',
    prompts: [
      { q: 'My beginner energy is…', a: 'All in, in the most anxious way possible.' },
      { q: 'An ideal first hangout…', a: 'The class, then a coffee to debrief our masterpieces.' },
      { q: 'Something I’ve always wanted to try…', a: 'Throwing a mug I’d actually drink from.' },
    ],
  },
  {
    id: 'jordan',
    firstName: 'Jordan',
    age: 31,
    neighborhood: 'Jamaica Plain',
    photo: '/images/people/jordan.png',
    gallery: [IMG.climbing, IMG.hiking, IMG.kayak],
    wantsToTryClassId: 'intro-bouldering',
    wantsToTryLabel: 'Intro to bouldering',
    availability: ['Weekday evenings', 'Sunday afternoons'],
    bio: 'Nurse with weird hours and a lot of energy to burn on my days off. New-ish to Boston and its indoor walls.',
    headlinePrompt: 'I will absolutely cheer too loudly when you send your first route.',
    interests: ['climbing', 'hiking', 'kayaking', 'tacos'],
    sharedInterests: ['climbing', 'hiking'],
    reason: 'You both want to start bouldering and can do weekday evenings.',
    socialPace: 'See how it goes',
    intentions: 'Looking for an accountability buddy to actually keep showing up.',
    prompts: [
      { q: 'My beginner energy is…', a: 'Nervous but game.' },
      { q: 'An ideal first hangout…', a: 'Climb, then tacos to celebrate not falling on our faces.' },
      { q: 'Something I’ve always wanted to try…', a: 'An outdoor climb once I stop being scared.' },
    ],
  },
  {
    id: 'priya',
    firstName: 'Priya',
    age: 30,
    neighborhood: 'Somerville',
    photo: '/images/people/priya.png',
    gallery: [IMG.watercolor, IMG.pottery, IMG.hiking],
    wantsToTryClassId: 'botanical-watercolor',
    wantsToTryLabel: 'Botanical watercolor basics',
    availability: ['Saturday afternoons', 'Sunday afternoons'],
    bio: 'Software engineer who needs a hobby that has nothing to do with a keyboard. Quiet company is my favorite company.',
    headlinePrompt: 'I’d like to learn to paint the plants in my apartment.',
    interests: ['watercolor', 'pottery', 'hiking', 'bookstores'],
    sharedInterests: ['watercolor', 'pottery'],
    reason: 'You’re both into calm, crafty weekends and free Saturday afternoons.',
    socialPace: 'Just the class',
    intentions: 'Prefers a gentle pace: one relaxed class at a time, no pressure to be best friends.',
    prompts: [
      { q: 'My beginner energy is…', a: 'Curious and a little quiet.' },
      { q: 'An ideal first hangout…', a: 'Just the class, honestly. Maybe tea if we click.' },
      { q: 'Something I’ve always wanted to try…', a: 'Keeping a little painted nature journal.' },
    ],
  },
  {
    id: 'marcus',
    firstName: 'Marcus',
    age: 29,
    neighborhood: 'Allston',
    photo: '/images/people/marcus.png',
    gallery: [IMG.film, IMG.salsa, IMG.painting],
    wantsToTryClassId: 'shoot-film',
    wantsToTryLabel: 'Shoot film in the city',
    availability: ['Weekday evenings', 'Sunday afternoons'],
    bio: 'Grad student and certified overthinker. I like projects with a tangible result I can hold at the end.',
    headlinePrompt: 'I have a film camera and could use some help figuring it out.',
    interests: ['film photography', 'salsa', 'painting', 'record stores'],
    sharedInterests: ['film photography'],
    reason: 'You’re both curious about film photography around Cambridge.',
    socialPace: 'Coffee afterward',
    intentions: 'Hoping to find a couple of hobby friends for regular low-key hangs.',
    prompts: [
      { q: 'My beginner energy is…', a: 'Curious, with too many browser tabs open.' },
      { q: 'An ideal first hangout…', a: 'Shoot a roll, then coffee to compare bad photos.' },
      { q: 'Something I’ve always wanted to try…', a: 'Developing my own black-and-white film.' },
    ],
  },
  {
    id: 'elena',
    firstName: 'Elena',
    age: 32,
    neighborhood: 'South End',
    photo: '/images/people/elena.png',
    gallery: [IMG.pasta, IMG.bread, IMG.salsa],
    wantsToTryClassId: 'fresh-pasta',
    wantsToTryLabel: 'Fresh pasta night',
    availability: ['Weekday evenings', 'Saturday afternoons'],
    bio: 'Marketing lead who cooks to unwind but keeps making dinner for one. Time to fix that.',
    headlinePrompt: 'I bring the appetite if you bring the questionable knife skills.',
    interests: ['pasta making', 'bread baking', 'salsa', 'farmers markets'],
    sharedInterests: ['pasta making', 'bread baking'],
    reason: 'You’re both into hands-on cooking classes on weeknights.',
    socialPace: 'See how it goes',
    intentions: 'Wants a buddy to try the whole cooking-class circuit with over a few months.',
    prompts: [
      { q: 'My beginner energy is…', a: 'Confidently wrong, then corrected.' },
      { q: 'An ideal first hangout…', a: 'Cook, eat what we made, linger at the table.' },
      { q: 'Something I’ve always wanted to try…', a: 'Making filled pasta without it exploding.' },
    ],
  },
  {
    id: 'tariq',
    firstName: 'Tariq',
    age: 33,
    neighborhood: 'Cambridge',
    photo: '/images/people/tariq.png',
    gallery: [IMG.salsa, IMG.dance, IMG.film],
    wantsToTryClassId: 'salsa-social',
    wantsToTryLabel: 'Salsa social for beginners',
    availability: ['Weekday evenings', 'Sunday evenings'],
    bio: 'Architect who is great at planning buildings and terrible at planning fun. Working on the second part.',
    headlinePrompt: 'Let’s be the two beginners counting steps under our breath.',
    interests: ['salsa', 'contemporary dance', 'film photography', 'jazz'],
    sharedInterests: ['salsa', 'dance'],
    reason: 'You both want to try salsa and can do weekday evenings.',
    socialPace: 'Coffee afterward',
    intentions: 'Looking for someone to take a weekly dance class with.',
    prompts: [
      { q: 'My beginner energy is…', a: 'Nervous but game, and secretly competitive.' },
      { q: 'An ideal first hangout…', a: 'The lesson, then stay for a bit of the social.' },
      { q: 'Something I’ve always wanted to try…', a: 'Actually leading a turn without apologizing.' },
    ],
  },
  {
    id: 'nina',
    firstName: 'Nina',
    age: 28,
    neighborhood: 'Somerville',
    photo: '/images/people/nina.png',
    gallery: [IMG.pottery, IMG.jewelry, IMG.watercolor],
    wantsToTryClassId: 'wheel-throwing',
    wantsToTryLabel: 'Wheel throwing for beginners',
    availability: ['Saturday afternoons', 'Sunday afternoons'],
    bio: 'UX researcher and lifelong maker of half-finished projects. Pottery is next on the list.',
    headlinePrompt: 'Here to get clay everywhere and make a friend in the process.',
    interests: ['pottery', 'jewelry making', 'watercolor', 'baking'],
    sharedInterests: ['pottery', 'jewelry making'],
    reason: 'You’re both pottery beginners in Somerville, free Saturday afternoons.',
    socialPace: 'See how it goes',
    intentions: 'Would love a crafty buddy to rotate through beginner maker classes.',
    prompts: [
      { q: 'My beginner energy is…', a: 'All in and slightly messy.' },
      { q: 'An ideal first hangout…', a: 'Make stuff, then wander for snacks.' },
      { q: 'Something I’ve always wanted to try…', a: 'A whole matching mug set, eventually.' },
    ],
  },
  {
    id: 'sofia',
    firstName: 'Sofia',
    age: 31,
    neighborhood: 'Beacon Hill',
    photo: '/images/people/sofia.png',
    gallery: [IMG.kayak, IMG.hiking, IMG.pottery],
    wantsToTryClassId: 'charles-kayak',
    wantsToTryLabel: 'Charles River kayak basics',
    availability: ['Saturday mornings', 'Sunday afternoons'],
    bio: 'Physical therapist who is happiest near water. Trying to spend less time indoors this fall.',
    headlinePrompt: 'I promise not to splash you (much) on the Charles.',
    interests: ['kayaking', 'hiking', 'pottery', 'swimming'],
    sharedInterests: ['kayaking', 'hiking'],
    reason: 'You both want to get on the water and can do weekend mornings.',
    socialPace: 'Coffee afterward',
    intentions: 'Looking for an outdoorsy weekend buddy before it gets cold.',
    prompts: [
      { q: 'My beginner energy is…', a: 'Calm and ready to get a little wet.' },
      { q: 'An ideal first hangout…', a: 'Paddle, then coffee on the Esplanade.' },
      { q: 'Something I’ve always wanted to try…', a: 'A longer river trip once I’ve got the basics.' },
    ],
  },
]

export const CONVERSATION_STARTERS: Record<string, string[]> = {
  Pottery: [
    'Have you taken a pottery class before?',
    'Morning or evening class person?',
    'Confession: I have watched way too many pottery videos.',
  ],
  Cooking: [
    'What are we making first, and can I eat all of it?',
    'Any allergies I should flag when we plan?',
    'I vote we split the recipe card and both take photos.',
  ],
  Dance: [
    'Fair warning: I have two left feet but a good attitude.',
    'Want to grab the beginner lesson before the social?',
    'Counting out loud together, deal?',
  ],
  Climbing: [
    'Are we the “try hard” type or the “take breaks” type?',
    'Evenings work better for me. How about you?',
    'Do we need to rent climbing shoes?',
  ],
  Art: [
    'Low bar: let’s just make one thing we don’t hate.',
    'Afternoon light class or evening?',
    'I already know mine will be abstract on purpose.',
  ],
  Outdoors: [
    'How early is too early for you?',
    'I’m bringing snacks. Any requests?',
    'Rain plan or push to next weekend if it’s gross?',
  ],
}

export const PROMPT_QUESTIONS = [
  {
    q: 'My beginner energy is…',
    options: ['Curious', 'Nervous but game', 'All in'],
  },
  {
    q: 'An ideal first hangout…',
    options: ['Just the class', 'Coffee afterward', 'See how it goes'],
  },
  {
    q: 'Something I’ve always wanted to try…',
    options: [],
  },
]

export const TRAVEL_OPTIONS = [
  'Walkable from me',
  'A short T ride',
  'Anywhere in Greater Boston',
]

export const DEMO_MATCH_BUDDY_ID = 'maya'

export const DEFAULT_PROFILE: UserProfile = {
  name: 'You',
  age: 29,
  neighborhood: 'Cambridge',
  photo: '/images/people/sofia.png',
  hobbies: ['Pottery', 'Cooking', 'Art'],
  availability: ['Saturday afternoons', 'Weekday evenings'],
  dateRange: 'Next 2 weeks',
  budget: 75,
  travel: 'A short T ride',
  buddyAgeRange: [25, 38],
  genderPreference: 'Open to everyone',
  prompts: [
    { q: 'My beginner energy is…', a: 'All in' },
    { q: 'An ideal first hangout…', a: 'Coffee afterward' },
    { q: 'Something I’ve always wanted to try…', a: 'Throwing a bowl on a real wheel' },
  ],
}

export const SAMPLE_PHOTOS = [
  '/images/people/sofia.png',
  '/images/people/maya.png',
  '/images/people/priya.png',
  '/images/people/nina.png',
  '/images/people/elena.png',
  '/images/people/marcus.png',
]

export function seedConversations(): Record<string, Conversation> {
  const now = Date.now()
  return {
    jordan: {
      buddyId: 'jordan',
      classId: 'intro-bouldering',
      lastActivity: now - 1000 * 60 * 60 * 20,
      messages: [
        {
          id: 'm1',
          from: 'them',
          kind: 'text',
          text: 'Hi! This will be my first time climbing. Have you been before?',
          createdAt: now - 1000 * 60 * 60 * 26,
        },
        {
          id: 'm2',
          from: 'me',
          kind: 'text',
          text: 'Same, honestly. Want to do the Saturday intro session so we can be nervous together?',
          createdAt: now - 1000 * 60 * 60 * 25,
        },
        {
          id: 'm3',
          from: 'them',
          kind: 'text',
          text: 'Yes please. Evenings are usually easier for me but I can make a weekend work.',
          createdAt: now - 1000 * 60 * 60 * 21,
        },
        {
          id: 'm4',
          from: 'them',
          kind: 'proposal',
          createdAt: now - 1000 * 60 * 60 * 20,
          proposal: {
            id: 'prop-jordan-1',
            classId: 'intro-bouldering',
            date: '2026-09-21T00:00:00',
            time: '11:00 AM',
            location: 'Granite & Chalk, Somerville',
            pricePerPerson: 40,
            status: 'proposed',
            proposedBy: 'them',
          },
        },
      ],
    },
  }
}
